name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'   # Only build/push when a tag starting with v: is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: saadhaniftaj/endpoint-agent:${{ github.ref_name }},saadhaniftaj/endpoint-agent:latest 
